# Student Performance Data Analysis

## Import Libraries and Load Dataset

In [3]:
# Import Pandas and NumPy
import pandas as pd
import numpy as np

## Load the CSV Dataset

In [4]:
# Load the student performance dataset
df = pd.read_csv("StudentsPerformance.csv")

## View the First Five Rows

In [5]:
# Display the first five rows
df.head()

,gender,race/ethnicity,parental level of education,lunch,test preparation course,math score,reading score,writing score
0,female,group B,bachelor's degree,standard,none,72,72,74
1,female,group C,some college,standard,completed,69,90,88
2,female,group B,master's degree,standard,none,90,95,93
3,male,group A,associate's degree,free/reduced,none,47,57,44
4,male,group C,some college,standard,none,76,78,75

## Check the Number of Rows and Columns

In [6]:
# Display the number of rows and columns
df.shape

(1000, 8)

## Display Column Names

In [7]:
# Display all column names
df.columns

Index(['gender', 'race/ethnicity', 'parental level of education', 'lunch',
       'test preparation course', 'math score', 'reading score',
       'writing score'],
      dtype='str')

## Check Data Types

In [8]:
# Display the data type of each column
df.dtypes

gender                           str
race/ethnicity                   str
parental level of education      str
lunch                            str
test preparation course          str
math score                     int64
reading score                  int64
writing score                  int64
dtype: object

## Display Dataset Information

In [9]:
# Display column names, non-null counts, and data types
df.info()

<class 'pandas.DataFrame'>
RangeIndex: 1000 entries, 0 to 999
Data columns (total 8 columns):
 #   Column                       Non-Null Count  Dtype
---  ------                       --------------  -----
 0   gender                       1000 non-null   str
 1   race/ethnicity               1000 non-null   str
 2   parental level of education  1000 non-null   str
 3   lunch                        1000 non-null   str
 4   test preparation course      1000 non-null   str
 5   math score                   1000 non-null   int64
 6   reading score                1000 non-null   int64
 7   writing score                1000 non-null   int64
dtypes: int64(3), str(5)
memory usage: 62.6 KB

## Display Statistical Summary

In [10]:
# Summarize the numeric columns
df.describe()

       math score  reading score  writing score
count  1000.00000    1000.000000    1000.000000
mean     66.08900      69.169000      68.054000
std      15.16308      14.600192      15.195657
min       0.00000      17.000000      10.000000
25%      57.00000      59.000000      57.750000
50%      66.00000      70.000000      69.000000
75%      77.00000      79.000000      79.000000
max     100.00000     100.000000     100.000000

## View the Last Five Rows

In [11]:
# Display the last five rows
df.tail()

,gender,race/ethnicity,parental level of education,lunch,test preparation course,math score,reading score,writing score
995,female,group E,master's degree,standard,completed,88,99,95
996,male,group C,high school,free/reduced,none,62,55,55
997,female,group C,high school,free/reduced,completed,59,71,65
998,female,group D,some college,standard,completed,68,78,77
999,female,group D,some college,free/reduced,none,77,86,86

## Calculate the Mean

In [12]:
# Calculate the mean for all numeric columns
df.mean(numeric_only=True)

# Calculate the average math score
df["math score"].mean()

np.float64(66.089)

## Calculate the Median

In [13]:
# Find the middle math score
df["math score"].median()

np.float64(66.0)

## Calculate the Mode

In [14]:
# Find the most frequent math score
df["math score"].mode()

0    65
Name: math score, dtype: int64

## Calculate Variance

In [15]:
# Calculate the variance of math scores
df["math score"].var()

np.float64(229.91899799799796)

## Calculate Standard Deviation

In [16]:
# Calculate the standard deviation of math scores
df["math score"].std()

np.float64(15.16308009600945)

## Find the Minimum Value

In [17]:
# Find the minimum reading score
df["reading score"].min()

np.int64(17)

## Find the Maximum Value

In [18]:
# Count the available math score values
df["math score"].count()

np.int64(1000)

## Count Non-Missing Values

In [19]:
# Count the available math score values
df["math score"].count()

np.int64(1000)

## Display Unique Values

In [20]:
# Display unique gender categories
df["gender"].unique()

<StringArray>
['female', 'male']
Length: 2, dtype: str

## Count Unique Values

In [21]:
# Count the number of unique gender categories
df["gender"].nunique()

2

## Display Value Frequencies

In [23]:
# Count students in each gender category
df["gender"].value_counts()

gender
female    518
male      482
Name: count, dtype: int64

## Identify Missing Values

In [24]:
# Count students in each gender category
df["gender"].value_counts()

gender
female    518
male      482
Name: count, dtype: int64

## Count Missing Values

In [25]:
# Count missing values in each column
df.isnull().sum()

gender                         0
race/ethnicity                 0
parental level of education    0
lunch                          0
test preparation course        0
math score                     0
reading score                  0
writing score                  0
dtype: int64

## Calculate Missing Value Percentage

In [26]:
# Calculate the percentage of missing values in each column
df.isnull().mean() * 100

gender                         0.0
race/ethnicity                 0.0
parental level of education    0.0
lunch                          0.0
test preparation course        0.0
math score                     0.0
reading score                  0.0
writing score                  0.0
dtype: float64

## Remove Rows with Missing Values

In [27]:
# Display data after removing rows containing missing values
# The original df is unchanged unless you assign the result
df.dropna()

,gender,race/ethnicity,parental level of education,lunch,test preparation course,math score,reading score,writing score
0,female,group B,bachelor's degree,standard,none,72,72,74
1,female,group C,some college,standard,completed,69,90,88
2,female,group B,master's degree,standard,none,90,95,93
3,male,group A,associate's degree,free/reduced,none,47,57,44
4,male,group C,some college,standard,none,76,78,75
...,...,...,...,...,...,...,...,...
995,female,group E,master's degree,standard,completed,88,99,95
996,male,group C,high school,free/reduced,none,62,55,55
997,female,group C,high school,free/reduced,completed,59,71,65
998,female,group D,some college,standard,completed,68,78,77
999,female,group D,some college,free/reduced,none,77,86,86

## Fill Missing Values

In [28]:
# Display data with missing values replaced by 0
# The original df is unchanged unless you assign the result
df.fillna(0)

,gender,race/ethnicity,parental level of education,lunch,test preparation course,math score,reading score,writing score
0,female,group B,bachelor's degree,standard,none,72,72,74
1,female,group C,some college,standard,completed,69,90,88
2,female,group B,master's degree,standard,none,90,95,93
3,male,group A,associate's degree,free/reduced,none,47,57,44
4,male,group C,some college,standard,none,76,78,75
...,...,...,...,...,...,...,...,...
995,female,group E,master's degree,standard,completed,88,99,95
996,male,group C,high school,free/reduced,none,62,55,55
997,female,group C,high school,free/reduced,completed,59,71,65
998,female,group D,some college,standard,completed,68,78,77
999,female,group D,some college,free/reduced,none,77,86,86

## Identify Duplicate Rows

In [29]:
# Identify which rows are duplicates
df.duplicated()

0      False
1      False
2      False
3      False
4      False
       ...
995    False
996    False
997    False
998    False
999    False
Length: 1000, dtype: bool

## Count Duplicate Rows

In [30]:
# Count the number of duplicate rows
df.duplicated().sum()

np.int64(0)

## Remove Duplicate Rows

In [31]:
# Display data after removing duplicate rows
# The original df is unchanged unless you assign the result
df.drop_duplicates()

,gender,race/ethnicity,parental level of education,lunch,test preparation course,math score,reading score,writing score
0,female,group B,bachelor's degree,standard,none,72,72,74
1,female,group C,some college,standard,completed,69,90,88
2,female,group B,master's degree,standard,none,90,95,93
3,male,group A,associate's degree,free/reduced,none,47,57,44
4,male,group C,some college,standard,none,76,78,75
...,...,...,...,...,...,...,...,...
995,female,group E,master's degree,standard,completed,88,99,95
996,male,group C,high school,free/reduced,none,62,55,55
997,female,group C,high school,free/reduced,completed,59,71,65
998,female,group D,some college,standard,completed,68,78,77
999,female,group D,some college,free/reduced,none,77,86,86

## Select One Column

In [32]:
# Select the math score column
df["math score"]

0      72
1      69
2      90
3      47
4      76
       ..
995    88
996    62
997    59
998    68
999    77
Name: math score, Length: 1000, dtype: int64

## Select Multiple Columns

In [33]:
# Select gender and all three subject score columns
df[["gender", "math score", "reading score", "writing score"]]

     gender  math score  reading score  writing score
0    female          72             72             74
1    female          69             90             88
2    female          90             95             93
3      male          47             57             44
4      male          76             78             75
..      ...         ...            ...            ...
995  female          88             99             95
996    male          62             55             55
997  female          59             71             65
998  female          68             78             77
999  female          77             86             86

[1000 rows x 4 columns]

## Select Rows by Position

In [ ]:
# Select the first five rows by position
df.iloc[0:5]

## Filter Students by a Condition

In [35]:
# Display students whose math score is greater than 80
df[df["math score"] > 80]

,gender,race/ethnicity,parental level of education,lunch,test preparation course,math score,reading score,writing score
2,female,group B,master's degree,standard,none,90,95,93
6,female,group B,some college,standard,completed,88,95,92
16,male,group C,high school,standard,none,88,89,86
34,male,group E,some college,standard,none,97,87,82
35,male,group E,associate's degree,standard,completed,81,81,79
...,...,...,...,...,...,...,...,...
979,female,group C,associate's degree,standard,none,91,95,94
981,male,group D,some high school,standard,none,81,78,78
987,male,group E,some high school,standard,completed,81,75,76
990,male,group E,high school,free/reduced,completed,86,81,75
995,female,group E,master's degree,standard,completed,88,99,95

## Sort Data

In [37]:
# Sort students by math score in ascending order
df.sort_values("math score")

,gender,race/ethnicity,parental level of education,lunch,test preparation course,math score,reading score,writing score
59,female,group C,some high school,free/reduced,none,0,17,10
980,female,group B,high school,free/reduced,none,8,24,23
17,female,group B,some high school,free/reduced,none,18,32,28
787,female,group B,some college,standard,none,19,38,32
145,female,group C,some college,free/reduced,none,22,39,33
...,...,...,...,...,...,...,...,...
623,male,group A,some college,standard,completed,100,96,86
625,male,group D,some college,standard,completed,100,97,99
962,female,group E,associate's degree,standard,none,100,100,100
458,female,group E,bachelor's degree,standard,none,100,100,100
916,male,group E,bachelor's degree,standard,completed,100,100,100

## Rename a Column

In [38]:
# Rename the parental education column
# This displays the renamed dataframe without changing the original df
df.rename(columns={"parental level of education": "parental_education"})

,gender,race/ethnicity,parental_education,lunch,test preparation course,math score,reading score,writing score
0,female,group B,bachelor's degree,standard,none,72,72,74
1,female,group C,some college,standard,completed,69,90,88
2,female,group B,master's degree,standard,none,90,95,93
3,male,group A,associate's degree,free/reduced,none,47,57,44
4,male,group C,some college,standard,none,76,78,75
...,...,...,...,...,...,...,...,...
995,female,group E,master's degree,standard,completed,88,99,95
996,male,group C,high school,free/reduced,none,62,55,55
997,female,group C,high school,free/reduced,completed,59,71,65
998,female,group D,some college,standard,completed,68,78,77
999,female,group D,some college,free/reduced,none,77,86,86

## Create a New Column

In [39]:
# Calculate the total of math, reading, and writing scores
df["total score"] = df["math score"] + df["reading score"] + df["writing score"]

# Display the first five rows with the new column
df.head()

,gender,race/ethnicity,parental level of education,lunch,test preparation course,math score,reading score,writing score,total score
0,female,group B,bachelor's degree,standard,none,72,72,74,218
1,female,group C,some college,standard,completed,69,90,88,247
2,female,group B,master's degree,standard,none,90,95,93,278
3,male,group A,associate's degree,free/reduced,none,47,57,44,148
4,male,group C,some college,standard,none,76,78,75,229

In [40]:
## # Display the dataframe without the writing score column
# The original df remains unchanged
df.drop(columns=["writing score"])

,gender,race/ethnicity,parental level of education,lunch,test preparation course,math score,reading score,total score
0,female,group B,bachelor's degree,standard,none,72,72,218
1,female,group C,some college,standard,completed,69,90,247
2,female,group B,master's degree,standard,none,90,95,278
3,male,group A,associate's degree,free/reduced,none,47,57,148
4,male,group C,some college,standard,none,76,78,229
...,...,...,...,...,...,...,...,...
995,female,group E,master's degree,standard,completed,88,99,282
996,male,group C,high school,free/reduced,none,62,55,172
997,female,group C,high school,free/reduced,completed,59,71,195
998,female,group D,some college,standard,completed,68,78,223
999,female,group D,some college,free/reduced,none,77,86,249

## Group Data

In [41]:
# Group student records by gender
df.groupby("gender")

## Group Data and Calculate Average

In [42]:
# Calculate the average math score for each gender
df.groupby("gender")["math score"].mean()

gender
female    63.633205
male      68.728216
Name: math score, dtype: float64

## Combine Datasets Using Concatenation

In [43]:
# Create two small dataframes from separate row ranges
df1 = df.iloc[0:5].copy()
df2 = df.iloc[5:10].copy()

# Combine the two dataframes row-wise
pd.concat([df1, df2])

,gender,race/ethnicity,parental level of education,lunch,test preparation course,math score,reading score,writing score,total score
0,female,group B,bachelor's degree,standard,none,72,72,74,218
1,female,group C,some college,standard,completed,69,90,88,247
2,female,group B,master's degree,standard,none,90,95,93,278
3,male,group A,associate's degree,free/reduced,none,47,57,44,148
4,male,group C,some college,standard,none,76,78,75,229
5,female,group B,associate's degree,standard,none,71,83,78,232
6,female,group B,some college,standard,completed,88,95,92,275
7,male,group B,some college,free/reduced,none,40,43,39,122
8,male,group D,high school,free/reduced,completed,64,64,67,195
9,female,group B,high school,free/reduced,none,38,60,50,148

## Merge Datasets

In [44]:
# Create two dataframes with a shared ID
df1 = df[["gender", "math score"]].copy()
df1["ID"] = df1.index

df2 = df[["reading score"]].copy()
df2["ID"] = df2.index

# Merge using the common ID column
pd.merge(df1, df2, on="ID")

     gender  math score   ID  reading score
0    female          72    0             72
1    female          69    1             90
2    female          90    2             95
3      male          47    3             57
4      male          76    4             78
..      ...         ...  ...            ...
995  female          88  995             99
996    male          62  996             55
997  female          59  997             71
998  female          68  998             78
999  female          77  999             86

[1000 rows x 4 columns]

## Rename a Column Permanently