# Library Data — Handling Missing Values and Encoding

## Import pandas

In [23]:
# Import pandas library
import pandas as pd

## Create the library dataset

In [22]:
# Create a library dataset with missing values
data = {
    'Book': ['Python', 'Java', 'C Programming', 'SQL', 'Python', 'Java'],
    'Price': [400, 500, None, 350, 400, None],
    'Rating': [4, 5, 3, None, 4, 5],
    'Category': ['Programming', 'Programming', None, 'Database', 'Programming', 'Programming'],
    'Publisher': ['ABC', 'XYZ', 'ABC', None, 'ABC', 'XYZ']
}

# Convert dictionary into a DataFrame
df = pd.DataFrame(data)

# Display the dataset
print(df)

            Book  Price  Rating     Category Publisher
0         Python  400.0     4.0  Programming       ABC
1           Java  500.0     5.0  Programming       XYZ
2  C Programming    NaN     3.0          NaN       ABC
3            SQL  350.0     NaN     Database       NaN
4         Python  400.0     4.0  Programming       ABC
5           Java    NaN     5.0  Programming       XYZ

## Basic EDA operations

In [20]:

# Display the first five rows
df.head()

            Book  Price  Rating     Category Publisher
0         Python  400.0     4.0  Programming       ABC
1           Java  500.0     5.0  Programming       XYZ
2  C Programming    NaN     3.0          NaN       ABC
3            SQL  350.0     NaN     Database       NaN
4         Python  400.0     4.0  Programming       ABC

In [12]:

# Display the last five rows
df.tail()

            Book  Price  Rating     Category Publisher
1           Java  500.0     5.0  Programming       XYZ
2  C Programming    NaN     3.0          NaN       ABC
3            SQL  350.0     NaN     Database       NaN
4         Python  400.0     4.0  Programming       ABC
5           Java    NaN     5.0  Programming       XYZ

In [13]:

# Display the number of rows and columns
df.shape

(6, 5)

In [14]:

# Display all column names
df.columns

Index(['Book', 'Price', 'Rating', 'Category', 'Publisher'], dtype='str')

In [15]:

# Display the data type of each column
df.dtypes

Book             str
Price        float64
Rating       float64
Category         str
Publisher        str
dtype: object

In [19]:

# Display dataset information
df.info()

<class 'pandas.DataFrame'>
RangeIndex: 6 entries, 0 to 5
Data columns (total 5 columns):
 #   Column     Non-Null Count  Dtype
---  ------     --------------  -----
 0   Book       6 non-null      str
 1   Price      4 non-null      float64
 2   Rating     5 non-null      float64
 3   Category   5 non-null      str
 4   Publisher  5 non-null      str
dtypes: float64(2), str(3)
memory usage: 372.0 bytes

## Identify missing values

In [24]:
# Identify missing values in each cell
print(df.isnull())

    Book  Price  Rating  Category  Publisher
0  False  False   False     False      False
1  False  False   False     False      False
2  False   True   False      True      False
3  False  False    True     False       True
4  False  False   False     False      False
5  False   True   False     False      False

In [25]:
# Count missing values in each column
print(df.isnull().sum())

Book         0
Price        2
Rating       1
Category     1
Publisher    1
dtype: int64

## Mean imputation

In [26]:
# Fill missing Price values with the mean price
df['Price'] = df['Price'].fillna(df['Price'].mean())

# Display the updated dataset
print(df)

            Book  Price  Rating     Category Publisher
0         Python  400.0     4.0  Programming       ABC
1           Java  500.0     5.0  Programming       XYZ
2  C Programming  412.5     3.0          NaN       ABC
3            SQL  350.0     NaN     Database       NaN
4         Python  400.0     4.0  Programming       ABC
5           Java  412.5     5.0  Programming       XYZ

## Calculate mean separately

In [27]:
# Calculate the mean book price
print("Mean Price:", df['Price'].mean())

Mean Price: 412.5

## Calculate mode

In [28]:
# Calculate the most frequently occurring book price
print("Mode Price:", df['Price'].mode().tolist())

Mode Price: [400.0, 412.5]

In [29]:
# Calculate the most frequently occurring book rating
print("Mode Rating:", df['Rating'].mode().tolist())

Mode Rating: [4.0, 5.0]

In [30]:
# Calculate the most frequently occurring book category
print("Mode Category:", df['Category'].mode().tolist())

Mode Category: ['Programming']

## Recreate the original data for median imputation

In [32]:
# Recreate the original library dataset
data = {
    'Book': ['Python', 'Java', 'C Programming', 'SQL', 'Python', 'Java'],
    'Price': [400, 500, None, 350, 400, None],
    'Rating': [4, 5, 3, None, 4, 5],
    'Category': ['Programming', 'Programming', None, 'Database', 'Programming', 'Programming'],
    'Publisher': ['ABC', 'XYZ', 'ABC', None, 'ABC', 'XYZ']
}

# Convert dictionary into a DataFrame
df = pd.DataFrame(data)

## Median imputation

In [33]:
# Fill missing Price values with the median price
df['Price'] = df['Price'].fillna(df['Price'].median())

# Display the updated dataset
print(df)

            Book  Price  Rating     Category Publisher
0         Python  400.0     4.0  Programming       ABC
1           Java  500.0     5.0  Programming       XYZ
2  C Programming  400.0     3.0          NaN       ABC
3            SQL  350.0     NaN     Database       NaN
4         Python  400.0     4.0  Programming       ABC
5           Java  400.0     5.0  Programming       XYZ

## Forward fill

In [34]:
# Create library data with missing categories
data = {
    'Book': ['Python', 'Java', 'C Programming', 'SQL', 'HTML'],
    'Category': ['Programming', 'Programming', None, 'Database', None]
}

# Convert dictionary into a DataFrame
df = pd.DataFrame(data)

In [35]:
# Display data before forward fill
print("Before Forward Fill:")
print(df)

Before Forward Fill:
            Book     Category
0         Python  Programming
1           Java  Programming
2  C Programming          NaN
3            SQL     Database
4           HTML          NaN

In [36]:
# Fill missing categories with the previous available category
df['Category'] = df['Category'].ffill()

# Display data after forward fill
print("\nAfter Forward Fill:")
print(df)

After Forward Fill:
            Book     Category
0         Python  Programming
1           Java  Programming
2  C Programming  Programming
3            SQL     Database
4           HTML     Database

In [42]:
# Install scikit-learn if it is not already installed
%pip install scikit-learn

Collecting scikit-learn
  Downloading scikit_learn-1.9.1-cp313-cp313-win_amd64.whl.metadata (9.3 kB)
Requirement already satisfied: numpy>=1.24.1 in C:\Users\Admin\AppData\Local\Programs\Python\Python313\Lib\site-packages (from scikit-learn) (2.5.3)
Requirement already satisfied: scipy>=1.10.0 in C:\Users\Admin\AppData\Local\Programs\Python\Python313\Lib\site-packages (from scikit-learn) (1.18.1)
Collecting joblib>=1.4.0 (from scikit-learn)
  Downloading joblib-1.6.0-py3-none-any.whl.metadata (6.5 kB)
Collecting narwhals>=2.0.1 (from scikit-learn)
  Downloading narwhals-2.27.1-py3-none-any.whl.metadata (15 kB)
Collecting threadpoolctl>=3.5.0 (from scikit-learn)
  Downloading threadpoolctl-3.7.0-py3-none-any.whl.metadata (24 kB)
Collecting cloudpickle>=3.0 (from joblib>=1.4.0->scikit-learn)
  Downloading cloudpickle-3.1.2-py3-none-any.whl.metadata (7.1 kB)
Downloading scikit_learn-1.9.1-cp313-cp313-win_amd64.whl (8.2 MB)
   ---------------------------------------- 0.0/8.2 MB ? eta -:--:--
   --- ------------------------------------ 0.8/8.2 MB 5.0 MB/s eta 0:00:02
   ------- -------------------------------- 1.6/8.2 MB 4.6 MB/s eta 0:00:02
   ----------- ---------------------------- 2.4/8.2 MB 4.4 MB/s eta 0:00:02
   --------------- ------------------------ 3.1/8.2 MB 3.9 MB/s eta 0:00:02
   ----------------- ---------------------- 3.7/8.2 MB 3.9 MB/s eta 0:00:02
   --------------------- ------------------ 4.5/8.2 MB 3.7 MB/s eta 0:00:02
   ------------------------- -------------- 5.2/8.2 MB 3.7 MB/s eta 0:00:01
   ---------------------------- ----------- 5.8/8.2 MB 3.6 MB/s eta 0:00:01
   ------------------------------- -------- 6.6/8.2 MB 3.6 MB/s eta 0:00:01
   ---------------------------------- ----- 7.1/8.2 MB 3.5 MB/s eta 0:00:01
   ----------------------------------- ---- 7.3/8.2 MB 3.3 MB/s eta 0:00:01
   ------------------------------------ --- 7.6/8.2 MB 3.2 MB/s eta 0:00:01
   ---------------------------------------  8.1/8.2 MB 3.1 MB/s eta 0:00:01
   ---------------------------------------- 8.2/8.2 MB 3.0 MB/s  0:00:02
Downloading joblib-1.6.0-py3-none-any.whl (306 kB)
Downloading cloudpickle-3.1.2-py3-none-any.whl (22 kB)
Downloading narwhals-2.27.1-py3-none-any.whl (483 kB)
Downloading threadpoolctl-3.7.0-py3-none-any.whl (26 kB)
Installing collected packages: threadpoolctl, narwhals, cloudpickle, joblib, scikit-learn

   -------- ------------------------------- 1/5 [narwhals]
   -------- ------------------------------- 1/5 [narwhals]
   -------- ------------------------------- 1/5 [narwhals]
   -------- ------------------------------- 1/5 [narwhals]
   -------- ------------------------------- 1/5 [narwhals]
   -------- ------------------------------- 1/5 [narwhals]
   -------- ------------------------------- 1/5 [narwhals]
   -------- ------------------------------- 1/5 [narwhals]
   -------- ------------------------------- 1/5 [narwhals]
   -------- ------------------------------- 1/5 [narwhals]
   -------- ------------------------------- 1/5 [narwhals]
   -------- ------------------------------- 1/5 [narwhals]
   -------- ------------------------------- 1/5 [narwhals]
   -------- ------------------------------- 1/5 [narwhals]
   -------- ------------------------------- 1/5 [narwhals]
   -------- ------------------------------- 1/5 [narwhals]
   -------- ------------------------------- 1/5 [narwhals]
   -------- ------------------------------- 1/5 [narwhals]
   -------- ------------------------------- 1/5 [narwhals]
   -------- ------------------------------- 1/5 [narwhals]
   -------- ------------------------------- 1/5 [narwhals]
   -------- ------------------------------- 1/5 [narwhals]
   -------- ------------------------------- 1/5 [narwhals]
   -------- ------------------------------- 1/5 [narwhals]
   -------- ------------------------------- 1/5 [narwhals]
   -------- ------------------------------- 1/5 [narwhals]
   -------- ------------------------------- 1/5 [narwhals]
   -------- ------------------------------- 1/5 [narwhals]
   -------- ------------------------------- 1/5 [narwhals]
   -------- ------------------------------- 1/5 [narwhals]
   -------- ------------------------------- 1/5 [narwhals]
   -------- ------------------------------- 1/5 [narwhals]
   -------- ------------------------------- 1/5 [narwhals]
   -------- ------------------------------- 1/5 [narwhals]
   -------- ------------------------------- 1/5 [narwhals]
   -------- ------------------------------- 1/5 [narwhals]
   -------- ------------------------------- 1/5 [narwhals]
   -------- ------------------------------- 1/5 [narwhals]
   -------- ------------------------------- 1/5 [narwhals]
   ------------------------ --------------- 3/5 [joblib]
   ------------------------ --------------- 3/5 [joblib]
   ------------------------ --------------- 3/5 [joblib]
   ------------------------ --------------- 3/5 [joblib]
   ------------------------ --------------- 3/5 [joblib]
   ------------------------ --------------- 3/5 [joblib]
   ------------------------ --------------- 3/5 [joblib]
   ------------------------ --------------- 3/5 [joblib]
   ------------------------ --------------- 3/5 [joblib]
   ------------------------ --------------- 3/5 [joblib]
   ------------------------ --------------- 3/5 [joblib]
   ------------------------ --------------- 3/5 [joblib]
   ------------------------ --------------- 3/5 [joblib]
   ------------------------ --------------- 3/5 [joblib]
   ------------------------ --------------- 3/5 [joblib]
   ------------------------ --------------- 3/5 [joblib]
   ------------------------ --------------- 3/5 [joblib]
   ------------------------ --------------- 3/5 [joblib]
   ------------------------ --------------- 3/5 [joblib]
   ------------------------ --------------- 3/5 [joblib]
   -------------------------------- ------- 4/5 [scikit-learn]
   -------------------------------- ------- 4/5 [scikit-learn]
   -------------------------------- ------- 4/5 [scikit-learn]
   -------------------------------- ------- 4/5 [scikit-learn]
   -------------------------------- ------- 4/5 [scikit-learn]
   -------------------------------- ------- 4/5 [scikit-learn]
   -------------------------------- ------- 4/5 [scikit-learn]
   -------------------------------- ------- 4/5 [scikit-learn]
   -------------------------------- ------- 4/5 [scikit-learn]
   -------------------------------- ------- 4/5 [scikit-learn]
   -------------------------------- ------- 4/5 [scikit-learn]
   -------------------------------- ------- 4/5 [scikit-learn]
   -------------------------------- ------- 4/5 [scikit-learn]
   -------------------------------- ------- 4/5 [scikit-learn]
   -------------------------------- ------- 4/5 [scikit-learn]
   -------------------------------- ------- 4/5 [scikit-learn]
   -------------------------------- ------- 4/5 [scikit-learn]
   -------------------------------- ------- 4/5 [scikit-learn]
   -------------------------------- ------- 4/5 [scikit-learn]
   -------------------------------- ------- 4/5 [scikit-learn]
   -------------------------------- ------- 4/5 [scikit-learn]
   -------------------------------- ------- 4/5 [scikit-learn]
   -------------------------------- ------- 4/5 [scikit-learn]
   -------------------------------- ------- 4/5 [scikit-learn]
   -------------------------------- ------- 4/5 [scikit-learn]
   -------------------------------- ------- 4/5 [scikit-learn]
   -------------------------------- ------- 4/5 [scikit-learn]
   -------------------------------- ------- 4/5 [scikit-learn]
   -------------------------------- ------- 4/5 [scikit-learn]
   -------------------------------- ------- 4/5 [scikit-learn]
   -------------------------------- ------- 4/5 [scikit-learn]
   -------------------------------- ------- 4/5 [scikit-learn]
   -------------------------------- ------- 4/5 [scikit-learn]
   -------------------------------- ------- 4/5 [scikit-learn]
   -------------------------------- ------- 4/5 [scikit-learn]
   -------------------------------- ------- 4/5 [scikit-learn]
   -------------------------------- ------- 4/5 [scikit-learn]
   -------------------------------- ------- 4/5 [scikit-learn]
   -------------------------------- ------- 4/5 [scikit-learn]
   -------------------------------- ------- 4/5 [scikit-learn]
   -------------------------------- ------- 4/5 [scikit-learn]
   -------------------------------- ------- 4/5 [scikit-learn]
   -------------------------------- ------- 4/5 [scikit-learn]
   -------------------------------- ------- 4/5 [scikit-learn]
   -------------------------------- ------- 4/5 [scikit-learn]
   -------------------------------- ------- 4/5 [scikit-learn]
   -------------------------------- ------- 4/5 [scikit-learn]
   -------------------------------- ------- 4/5 [scikit-learn]
   -------------------------------- ------- 4/5 [scikit-learn]
   -------------------------------- ------- 4/5 [scikit-learn]
   -------------------------------- ------- 4/5 [scikit-learn]
   -------------------------------- ------- 4/5 [scikit-learn]
   -------------------------------- ------- 4/5 [scikit-learn]
   -------------------------------- ------- 4/5 [scikit-learn]
   -------------------------------- ------- 4/5 [scikit-learn]
   -------------------------------- ------- 4/5 [scikit-learn]
   -------------------------------- ------- 4/5 [scikit-learn]
   -------------------------------- ------- 4/5 [scikit-learn]
   -------------------------------- ------- 4/5 [scikit-learn]
   -------------------------------- ------- 4/5 [scikit-learn]
   -------------------------------- ------- 4/5 [scikit-learn]
   -------------------------------- ------- 4/5 [scikit-learn]
   -------------------------------- ------- 4/5 [scikit-learn]
   -------------------------------- ------- 4/5 [scikit-learn]
   -------------------------------- ------- 4/5 [scikit-learn]
   -------------------------------- ------- 4/5 [scikit-learn]
   -------------------------------- ------- 4/5 [scikit-learn]
   -------------------------------- ------- 4/5 [scikit-learn]
   -------------------------------- ------- 4/5 [scikit-learn]
   -------------------------------- ------- 4/5 [scikit-learn]
   -------------------------------- ------- 4/5 [scikit-learn]
   -------------------------------- ------- 4/5 [scikit-learn]
   -------------------------------- ------- 4/5 [scikit-learn]
   -------------------------------- ------- 4/5 [scikit-learn]
   -------------------------------- ------- 4/5 [scikit-learn]
   -------------------------------- ------- 4/5 [scikit-learn]
   -------------------------------- ------- 4/5 [scikit-learn]
   -------------------------------- ------- 4/5 [scikit-learn]
   -------------------------------- ------- 4/5 [scikit-learn]
   -------------------------------- ------- 4/5 [scikit-learn]
   -------------------------------- ------- 4/5 [scikit-learn]
   -------------------------------- ------- 4/5 [scikit-learn]
   -------------------------------- ------- 4/5 [scikit-learn]
   -------------------------------- ------- 4/5 [scikit-learn]
   -------------------------------- ------- 4/5 [scikit-learn]
   -------------------------------- ------- 4/5 [scikit-learn]
   -------------------------------- ------- 4/5 [scikit-learn]
   -------------------------------- ------- 4/5 [scikit-learn]
   -------------------------------- ------- 4/5 [scikit-learn]
   -------------------------------- ------- 4/5 [scikit-learn]
   -------------------------------- ------- 4/5 [scikit-learn]
   -------------------------------- ------- 4/5 [scikit-learn]
   -------------------------------- ------- 4/5 [scikit-learn]
   -------------------------------- ------- 4/5 [scikit-learn]
   -------------------------------- ------- 4/5 [scikit-learn]
   -------------------------------- ------- 4/5 [scikit-learn]
   -------------------------------- ------- 4/5 [scikit-learn]
   -------------------------------- ------- 4/5 [scikit-learn]
   -------------------------------- ------- 4/5 [scikit-learn]
   -------------------------------- ------- 4/5 [scikit-learn]
   -------------------------------- ------- 4/5 [scikit-learn]
   -------------------------------- ------- 4/5 [scikit-learn]
   -------------------------------- ------- 4/5 [scikit-learn]
   -------------------------------- ------- 4/5 [scikit-learn]
   -------------------------------- ------- 4/5 [scikit-learn]
   -------------------------------- ------- 4/5 [scikit-learn]
   -------------------------------- ------- 4/5 [scikit-learn]
   -------------------------------- ------- 4/5 [scikit-learn]
   -------------------------------- ------- 4/5 [scikit-learn]
   -------------------------------- ------- 4/5 [scikit-learn]
   -------------------------------- ------- 4/5 [scikit-learn]
   -------------------------------- ------- 4/5 [scikit-learn]
   -------------------------------- ------- 4/5 [scikit-learn]
   -------------------------------- ------- 4/5 [scikit-learn]
   -------------------------------- ------- 4/5 [scikit-learn]
   -------------------------------- ------- 4/5 [scikit-learn]
   -------------------------------- ------- 4/5 [scikit-learn]
   -------------------------------- ------- 4/5 [scikit-learn]
   -------------------------------- ------- 4/5 [scikit-learn]
   -------------------------------- ------- 4/5 [scikit-learn]
   -------------------------------- ------- 4/5 [scikit-learn]
   -------------------------------- ------- 4/5 [scikit-learn]
   -------------------------------- ------- 4/5 [scikit-learn]
   -------------------------------- ------- 4/5 [scikit-learn]
   -------------------------------- ------- 4/5 [scikit-learn]
   -------------------------------- ------- 4/5 [scikit-learn]
   -------------------------------- ------- 4/5 [scikit-learn]
   -------------------------------- ------- 4/5 [scikit-learn]
   -------------------------------- ------- 4/5 [scikit-learn]
   -------------------------------- ------- 4/5 [scikit-learn]
   -------------------------------- ------- 4/5 [scikit-learn]
   -------------------------------- ------- 4/5 [scikit-learn]
   -------------------------------- ------- 4/5 [scikit-learn]
   -------------------------------- ------- 4/5 [scikit-learn]
   -------------------------------- ------- 4/5 [scikit-learn]
   -------------------------------- ------- 4/5 [scikit-learn]
   -------------------------------- ------- 4/5 [scikit-learn]
   -------------------------------- ------- 4/5 [scikit-learn]
   -------------------------------- ------- 4/5 [scikit-learn]
   -------------------------------- ------- 4/5 [scikit-learn]
   -------------------------------- ------- 4/5 [scikit-learn]
   -------------------------------- ------- 4/5 [scikit-learn]
   -------------------------------- ------- 4/5 [scikit-learn]
   -------------------------------- ------- 4/5 [scikit-learn]
   -------------------------------- ------- 4/5 [scikit-learn]
   -------------------------------- ------- 4/5 [scikit-learn]
   -------------------------------- ------- 4/5 [scikit-learn]
   -------------------------------- ------- 4/5 [scikit-learn]
   -------------------------------- ------- 4/5 [scikit-learn]
   -------------------------------- ------- 4/5 [scikit-learn]
   -------------------------------- ------- 4/5 [scikit-learn]
   -------------------------------- ------- 4/5 [scikit-learn]
   -------------------------------- ------- 4/5 [scikit-learn]
   -------------------------------- ------- 4/5 [scikit-learn]
   -------------------------------- ------- 4/5 [scikit-learn]
   -------------------------------- ------- 4/5 [scikit-learn]
   -------------------------------- ------- 4/5 [scikit-learn]
   -------------------------------- ------- 4/5 [scikit-learn]
   -------------------------------- ------- 4/5 [scikit-learn]
   -------------------------------- ------- 4/5 [scikit-learn]
   -------------------------------- ------- 4/5 [scikit-learn]
   -------------------------------- ------- 4/5 [scikit-learn]
   -------------------------------- ------- 4/5 [scikit-learn]
   -------------------------------- ------- 4/5 [scikit-learn]
   -------------------------------- ------- 4/5 [scikit-learn]
   -------------------------------- ------- 4/5 [scikit-learn]
   -------------------------------- ------- 4/5 [scikit-learn]
   -------------------------------- ------- 4/5 [scikit-learn]
   -------------------------------- ------- 4/5 [scikit-learn]
   -------------------------------- ------- 4/5 [scikit-learn]
   -------------------------------- ------- 4/5 [scikit-learn]
   -------------------------------- ------- 4/5 [scikit-learn]
   -------------------------------- ------- 4/5 [scikit-learn]
   -------------------------------- ------- 4/5 [scikit-learn]
   -------------------------------- ------- 4/5 [scikit-learn]
   -------------------------------- ------- 4/5 [scikit-learn]
   -------------------------------- ------- 4/5 [scikit-learn]
   -------------------------------- ------- 4/5 [scikit-learn]
   -------------------------------- ------- 4/5 [scikit-learn]
   -------------------------------- ------- 4/5 [scikit-learn]
   -------------------------------- ------- 4/5 [scikit-learn]
   -------------------------------- ------- 4/5 [scikit-learn]
   -------------------------------- ------- 4/5 [scikit-learn]
   -------------------------------- ------- 4/5 [scikit-learn]
   -------------------------------- ------- 4/5 [scikit-learn]
   -------------------------------- ------- 4/5 [scikit-learn]
   -------------------------------- ------- 4/5 [scikit-learn]
   -------------------------------- ------- 4/5 [scikit-learn]
   -------------------------------- ------- 4/5 [scikit-learn]
   -------------------------------- ------- 4/5 [scikit-learn]
   -------------------------------- ------- 4/5 [scikit-learn]
   -------------------------------- ------- 4/5 [scikit-learn]
   -------------------------------- ------- 4/5 [scikit-learn]
   -------------------------------- ------- 4/5 [scikit-learn]
   -------------------------------- ------- 4/5 [scikit-learn]
   -------------------------------- ------- 4/5 [scikit-learn]
   -------------------------------- ------- 4/5 [scikit-learn]
   -------------------------------- ------- 4/5 [scikit-learn]
   -------------------------------- ------- 4/5 [scikit-learn]
   -------------------------------- ------- 4/5 [scikit-learn]
   -------------------------------- ------- 4/5 [scikit-learn]
   -------------------------------- ------- 4/5 [scikit-learn]
   -------------------------------- ------- 4/5 [scikit-learn]
   -------------------------------- ------- 4/5 [scikit-learn]
   -------------------------------- ------- 4/5 [scikit-learn]
   -------------------------------- ------- 4/5 [scikit-learn]
   -------------------------------- ------- 4/5 [scikit-learn]
   -------------------------------- ------- 4/5 [scikit-learn]
   -------------------------------- ------- 4/5 [scikit-learn]
   -------------------------------- ------- 4/5 [scikit-learn]
   -------------------------------- ------- 4/5 [scikit-learn]
   -------------------------------- ------- 4/5 [scikit-learn]
   -------------------------------- ------- 4/5 [scikit-learn]
   -------------------------------- ------- 4/5 [scikit-learn]
   -------------------------------- ------- 4/5 [scikit-learn]
   -------------------------------- ------- 4/5 [scikit-learn]
   -------------------------------- ------- 4/5 [scikit-learn]
   -------------------------------- ------- 4/5 [scikit-learn]
   ---------------------------------------- 5/5 [scikit-learn]

Successfully installed cloudpickle-3.1.2 joblib-1.6.0 narwhals-2.27.1 scikit-learn-1.9.1 threadpoolctl-3.7.0
Note: you may need to restart the kernel to use updated packages.

[notice] A new release of pip is available: 26.1.2 -> 26.2.1
[notice] To update, run: C:\Users\Admin\AppData\Local\Programs\Python\Python313\python.exe -m pip install --upgrade pip

## Import LabelEncoder

In [43]:
# Import LabelEncoder for categorical encoding
from sklearn.preprocessing import LabelEncoder

## Create data for Label Encoding

In [38]:
# Create library category data
data = {
    'Book': ['Python', 'Java', 'C Programming', 'SQL'],
    'Category': ['Programming', 'Programming', 'Programming', 'Database']
}

# Convert dictionary into a DataFrame
df = pd.DataFrame(data)

# Display the dataset
print(df)

            Book     Category
0         Python  Programming
1           Java  Programming
2  C Programming  Programming
3            SQL     Database

## Perform Label Encoding

In [44]:
# Create a LabelEncoder object
encoder = LabelEncoder()

# Convert categories into numerical labels
df['Category_Encoded'] = encoder.fit_transform(df['Category'])

# Display the encoded dataset
print(df)

            Book     Category  Category_Encoded
0         Python  Programming                 1
1           Java  Programming                 1
2  C Programming  Programming                 1
3            SQL     Database                 0

In [45]:
# Display the category names used by the encoder
print(encoder.classes_)

['Database' 'Programming']

## Create data for One-Hot Encoding

In [46]:
# Import pandas library
import pandas as pd

# Create library category data
data = {
    'Book': ['Python', 'Java', 'C Programming', 'SQL'],
    'Category': ['Programming', 'Programming', 'Programming', 'Database']
}

# Convert dictionary into a DataFrame
df = pd.DataFrame(data)

# Display the dataset
print(df)

            Book     Category
0         Python  Programming
1           Java  Programming
2  C Programming  Programming
3            SQL     Database

## Perform One-Hot Encoding

In [47]:
# Create separate columns for each category
encoded_df = pd.get_dummies(df, columns=['Category'])

# Display the encoded dataset
print(encoded_df)

            Book  Category_Database  Category_Programming
0         Python              False                  True
1           Java              False                  True
2  C Programming              False                  True
3            SQL               True                 False

## One-Hot Encoding with 0 and 1

In [48]:
# Convert categories into integer columns containing 0 and 1
encoded_df = pd.get_dummies(
    df,
    columns=['Category'],
    dtype=int
)

# Display the encoded dataset
print(encoded_df)

            Book  Category_Database  Category_Programming
0         Python                  0                     1
1           Java                  0                     1
2  C Programming                  0                     1
3            SQL                  1                     0

## Count all missing values

In [49]:
# Count the total number of missing values in the dataset
print("Total Missing Values:", df.isnull().sum().sum())

Total Missing Values: 0

## Display only rows containing missing values

In [50]:
# Display rows that contain at least one missing value
print(df[df.isnull().any(axis=1)])

Empty DataFrame
Columns: [Book, Category]
Index: []

## Recreate your library dataset

In [53]:
# Import pandas
import pandas as pd

# Create library dataset with missing values
data = {
    'Book': ['Python', 'Java', 'C Programming', 'SQL', 'Python', 'Java'],
    'Price': [400, 500, None, 350, 400, None],
    'Rating': [4, 5, 3, None, 4, 5],
    'Category': ['Programming', 'Programming', None, 'Database', 'Programming', 'Programming'],
    'Publisher': ['ABC', 'XYZ', 'ABC', None, 'ABC', 'XYZ']
}

# Create DataFrame
df = pd.DataFrame(data)

# Display the dataset
print(df)

            Book  Price  Rating     Category Publisher
0         Python  400.0     4.0  Programming       ABC
1           Java  500.0     5.0  Programming       XYZ
2  C Programming    NaN     3.0          NaN       ABC
3            SQL  350.0     NaN     Database       NaN
4         Python  400.0     4.0  Programming       ABC
5           Java    NaN     5.0  Programming       XYZ

## Check missing values in one column

In [54]:
# Check missing values in the Price column
print(df['Price'].isnull().sum())

2

## Fill missing values with a fixed value

In [55]:
# Replace missing Publisher values with Unknown
df['Publisher'] = df['Publisher'].fillna('Unknown')

# Display the updated Publisher column
print(df['Publisher'])

0        ABC
1        XYZ
2        ABC
3    Unknown
4        ABC
5        XYZ
Name: Publisher, dtype: str

## Remove rows containing missing values

In [56]:
# Remove rows that contain missing values
df_clean = df.dropna()

# Display the cleaned dataset
print(df_clean)

     Book  Price  Rating     Category Publisher
0  Python  400.0     4.0  Programming       ABC
1    Java  500.0     5.0  Programming       XYZ
4  Python  400.0     4.0  Programming       ABC

## Remove columns containing missing values

In [57]:
# Remove columns that contain at least one missing value
df_no_missing_columns = df.dropna(axis=1)

# Display the result
print(df_no_missing_columns)

            Book Publisher
0         Python       ABC
1           Java       XYZ
2  C Programming       ABC
3            SQL   Unknown
4         Python       ABC
5           Java       XYZ

In [ ]:
## Backward fill